apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: nexclipper
  labels:
    app: nginx-exporter
    managed: exporterhub
spec:
  selector:
    matchLabels:
      app: nginx-exporter
      managed: exporterhub
  template:
    metadata:
      labels:
        app: nginx-exporter
        managed: exporterhub
    spec:
      containers:
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.9.0'
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: APP
          value: ${APP}
        - name: NAMESPACE
          value: ${NAMESPACE}
        - name: SVC
          value: ${SVC}
        - name: PORT
          value: ${PORT}
        args:
          # - '-nginx.scrape-uri=http://$(APP).$(NAMESPACE).$(SVC):$(PORT)/stub_status'
          - '-nginx.scrape-uri=http://nginx.default.svc.cluster.local:8080/stub_status'
        ports:
          - name: nginx-ex-port
            containerPort: 9113
            protocol: TCP
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-exporter
    managed: exporterhub
  name: nginx-exporter
  namespace: nexclipper
spec:
  ports:
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: metrics
  selector:
    app: nginx-exporter
  sessionAffinity: None
  type: ClusterIP

