- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: nexclipper-exporter
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: nexclipper;exporterhub
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_label_managed
  - action: replace
    source_labels: [__meta_kubernetes_service_label_app]
    target_label: component
  - action: replace
    source_labels: [__meta_kubernetes_service_label_managed]
    target_label: managed_by
  - action: replace
    source_labels: [__meta_kubernetes_pod_node_name]
    target_label: kubernetes_node
  - action: replace
    source_labels: [__meta_kubernetes_pod_controller_kind]
    target_label: kubernetes_node
  - action: replace
    source_labels: [__meta_kubernetes_pod_controller_name]
    target_label: kubernetes_node
  - action: replace
    source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - action: replace
    source_labels: [__meta_kubernetes_service_name]
    target_label: kubernetes_name